CREATE TABLE [dbo].[articulosest](
	[idarticulo] [int] NOT NULL,
	[marca] [varchar](3) NOT NULL,
	[modelo] [varchar](7) NOT NULL,
	[estilof] [varchar](14) NOT NULL,
	[descripc] [varchar](70) NOT NULL,
	[iddivisiones] [int] NOT NULL,
	[division] [varchar](30) NOT NULL,
	[iddepto] [int] NOT NULL,
	[depto] [varchar](30) NOT NULL,
	[idfamilia] [int] NOT NULL,
	[familia] [varchar](30) NOT NULL,
	[idlinea] [int] NOT NULL,
	[linea] [varchar](30) NOT NULL,
	[idl1] [int] NOT NULL,
	[l1] [varchar](30) NOT NULL,
	[idl2] [int] NOT NULL,
	[l2] [varchar](30) NOT NULL,
	[idl3] [int] NOT NULL,
	[l3] [varchar](30) NOT NULL,
	[idl4] [int] NOT NULL,
	[l4] [varchar](30) NOT NULL,
	[idl5] [int] NOT NULL,
	[l5] [varchar](30) NOT NULL,
	[idl6] [int] NOT NULL,
	[l6] [varchar](30) NOT NULL,
	[di] [varchar](3) NOT NULL,
	[de] [varchar](3) NOT NULL,
	[fa] [varchar](3) NOT NULL,
	[l] [varchar](3) NOT NULL,
	[cl1] [varchar](3) NOT NULL,
	[cl2] [varchar](3) NOT NULL,
	[cl3] [varchar](3) NOT NULL,
	[cl4] [varchar](3) NOT NULL,
	[cl5] [varchar](3) NOT NULL,
	[cl6] [varchar](3) NOT NULL,
	[proveedor] [varchar](3) NOT NULL,
	[medida] [varchar](3) NOT NULL,
	[fecha] [varchar](8) NOT NULL,
	[fecreci] [date] NOT NULL,
	[fecup] [date] NOT NULL,
	[idagrupacion] [int] NOT NULL,
	[diasinvideal] [int] NOT NULL,
	[vigenciaa] [date] NULL,
	[ClaveProdServ] [varchar](50) NULL,
	[ventaenlinea] [smallint] NULL,
 [web] BIT NULL, -- nuevo
    CONSTRAINT [PK_articulosest_idarticulo] PRIMARY KEY CLUSTERED 
(
	[idarticulo] ASC
)
)
GO
